project_identifier: geokrety
api_key_env: CROWDIN_API_KEY
base_path:
preserve_hierarchy: true
files:
  - source: /website/app/languages/messages.po.txt
    translation: /website/app/languages/%locale_with_underscore%.UTF-8/LC_MESSAGES/messages.po
    dest: messages.po
  - source: /website/app-templates/smarty/help-pages/en/help.html
    translation: /website/app-templates/smarty/help-pages/%two_letters_code%/help.html
    dest: help.html
