name: Get container ps

inputs:
  CONTAINER:
    default:
    description: The container name

runs:
  using: "composite"
  steps:
    - name: Get docker-compose ps ${{ inputs.CONTAINER && format('for container {0}', inputs.CONTAINER) }}
      shell: bash
      run: |
        for j in $(seq ${{ env.GK_INSTANCE_COUNT }}); do
          ((f = $j - 1))
          echo "::group::docker-compose ps ${{ inputs.CONTAINER }} - Instance:$f"
          make ps-single \
            GK_INSTANCE_ID=$j \
            CONTAINER="${{ inputs.CONTAINER }}"
          echo "::endgroup::"
        done
