BEGIN;
SELECT plan(47);

SELECT has_schema('stats', 'stats schema exists');
SELECT has_table('stats', 'backfill_progress', 'stats.backfill_progress exists');
SELECT has_table('stats', 'job_log', 'stats.job_log exists');
SELECT has_table('stats', 'continent_reference', 'stats.continent_reference exists');
SELECT has_table('stats', 'entity_counters_shard', 'stats.entity_counters_shard exists');
SELECT has_table('stats', 'daily_activity', 'stats.daily_activity exists');
SELECT has_table('stats', 'daily_active_users', 'stats.daily_active_users exists');
SELECT has_table('stats', 'daily_entity_counts', 'stats.daily_entity_counts exists');
SELECT has_table('stats', 'country_daily_stats', 'stats.country_daily_stats exists');
SELECT has_table('stats', 'gk_countries_visited', 'stats.gk_countries_visited exists');
SELECT has_table('stats', 'user_countries', 'stats.user_countries exists');
SELECT has_table('stats', 'gk_country_history', 'stats.gk_country_history exists');
SELECT has_table('stats', 'waypoints', 'stats.waypoints exists');
SELECT has_table('stats', 'gk_cache_visits', 'stats.gk_cache_visits exists');
SELECT has_table('stats', 'user_cache_visits', 'stats.user_cache_visits exists');
SELECT has_table('stats', 'gk_related_users', 'stats.gk_related_users exists');
SELECT has_table('stats', 'user_related_users', 'stats.user_related_users exists');
SELECT has_table('stats', 'hourly_activity', 'stats.hourly_activity exists');
SELECT has_table('stats', 'country_pair_flows', 'stats.country_pair_flows exists');
SELECT has_table('stats', 'gk_milestone_events', 'stats.gk_milestone_events exists');
SELECT has_table('stats', 'first_finder_events', 'stats.first_finder_events exists');
SELECT has_view('stats', 'v_waypoints_source_union', 'stats.v_waypoints_source_union exists');
SELECT has_function('stats', 'fn_seed_waypoints', ARRAY[]::text[], 'stats.fn_seed_waypoints exists');
SELECT has_function('stats', 'fn_snapshot_entity_counters', ARRAY[]::text[], 'stats.fn_snapshot_entity_counters exists');
SELECT has_function('stats', 'fn_seed_daily_activity', ARRAY['tstzrange'], 'stats.fn_seed_daily_activity exists');
SELECT has_function('stats', 'fn_snapshot_waypoints', ARRAY[]::text[], 'stats.fn_snapshot_waypoints exists');
SELECT has_function('stats', 'fn_snapshot_cache_visits', ARRAY[]::text[], 'stats.fn_snapshot_cache_visits exists');
SELECT has_function('stats', 'fn_snapshot_relations', ARRAY[]::text[], 'stats.fn_snapshot_relations exists');
SELECT has_function('stats', 'fn_snapshot_relationship_tables', ARRAY['daterange'], 'stats.fn_snapshot_relationship_tables exists');
SELECT has_function('stats', 'fn_snapshot_hourly_activity', ARRAY[]::text[], 'stats.fn_snapshot_hourly_activity exists');
SELECT has_function('stats', 'fn_snapshot_country_pair_flows', ARRAY[]::text[], 'stats.fn_snapshot_country_pair_flows exists');
SELECT has_function('geokrety', 'fn_current_geokret_country', ARRAY['bigint'], 'geokrety.fn_current_geokret_country exists');
SELECT has_function('geokrety', 'fn_gk_loves_activity', ARRAY[]::text[], 'geokrety.fn_gk_loves_activity exists');
SELECT has_trigger('geokrety', 'gk_loves', 'tr_gk_loves_activity', 'tr_gk_loves_activity exists');
SELECT has_function('geokrety', 'fn_gk_moves_emit_points_event', ARRAY[]::text[], 'geokrety.fn_gk_moves_emit_points_event exists');
SELECT has_trigger('geokrety', 'gk_moves', 'tr_gk_moves_emit_points_event', 'tr_gk_moves_emit_points_event exists');
SELECT has_function('geokrety', 'fn_gk_moves_milestones', ARRAY[]::text[], 'geokrety.fn_gk_moves_milestones exists');
SELECT has_function('stats', 'fn_detect_first_finder', ARRAY['bigint', 'bigint', 'bigint', 'smallint', 'timestamp with time zone'], 'stats.fn_detect_first_finder exists');
SELECT has_function('geokrety', 'fn_gk_moves_first_finder', ARRAY[]::text[], 'geokrety.fn_gk_moves_first_finder exists');
SELECT has_trigger('geokrety', 'gk_moves', 'tr_gk_moves_after_first_finder', 'tr_gk_moves_after_first_finder exists');
SELECT has_function('stats', 'fn_run_all_snapshots', ARRAY[]::text[], 'stats.fn_run_all_snapshots exists');
SELECT has_function('stats', 'fn_run_all_snapshots', ARRAY['text[]', 'tstzrange', 'integer'], 'scoped stats.fn_run_all_snapshots exists');
SELECT has_function('stats', 'fn_reconcile_stats', ARRAY[]::text[], 'stats.fn_reconcile_stats exists');
SELECT has_function('stats', 'fn_reconcile_stats', ARRAY['text[]', 'tstzrange'], 'scoped stats.fn_reconcile_stats exists');
SELECT has_view('stats', 'v_uc1_country_activity', 'stats.v_uc1_country_activity exists');
SELECT has_view('stats', 'v_uc10_cache_popularity', 'stats.v_uc10_cache_popularity exists');
SELECT has_view('stats', 'v_uc15_distance_records', 'stats.v_uc15_distance_records exists');

SELECT * FROM finish();
ROLLBACK;
