name: Run database tests

###############
# !!!!!!! Tests need the website to be up, as it needs db migrations to be applied
###############

runs:
  using: "composite"
  steps:

    - name: Install tools
      shell: bash
      run: |
        echo "::group::Install pgtap"
        command -v pg_prove || \
          ${APT_INSTALL} libtap-parser-sourcehandler-pgtap-perl libtap-formatter-html-perl
        echo "::endgroup::"

    - name: Run database tests
      shell: bash
      env:
        PGOPTIONS: --search_path=public,pgtap,geokrety
      run: |
        pg_prove -ot website/db/tests/test*.sql

        # Run a second time to generate an html output
        pg_prove -ot website/db/tests/test*.sql \
          -Q --formatter TAP::Formatter::HTML > database-test-result.html

    - name: "Show docker logs: postgres"
      if: failure()
      uses: ./.github/actions/docker-logs/
      with:
        CONTAINER: postgres
