FROM ypereirareis/php-cs-fixer

MAINTAINER Mathieu Alorent <contact@geokretymap.org>

# Install additional tools
RUN apt-get update \
    && apt-get install -y \
        moreutils \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/*

ADD https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.12.4/php-cs-fixer.phar /usr/local/bin/php-cs-fixer
RUN chmod +x /usr/local/bin/php-cs-fixer

