CREATE DATABASE  IF NOT EXISTS `geokrety-db` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `geokrety-db`;

DROP TABLE IF EXISTS `gk-waypointy-country`;
CREATE TABLE `gk-waypointy-country` (
  `kraj` varchar(200) COLLATE utf8_polish_ci NOT NULL,
  `country` varchar(200) COLLATE utf8_polish_ci DEFAULT NULL,
  UNIQUE KEY `unique_kraj` (`kraj`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci;

INSERT INTO `gk-waypointy-country` (`kraj`, `country`) VALUES
('Ägypten',	'Egypt'),
('Albania',	'Albania'),
('Albanien',	'Albania'),
('Łotwa',	'Latvia'),
('Argentyna',	'Argentina'),
('Armenia',	'Armenia'),
('Australien',	'Australia'),
('Austria',	'Australia'),
('Belarus (Weißrußland)',	'Belarus'),
('Belgia',	'Belgium'),
('Belgien',	'Belgium'),
('Białoruś',	'Belarus'),
('Bosnien-Herzegowina',	'Bosnia and Herzegovina'),
('Brasilien',	'Brazil'),
('Bułgaria',	'Bulgaria'),
('Bulgarien',	'Bulgaria'),
('Chiny',	'China'),
('Chorwacja',	'Croatia'),
('Costa Rica',	'Costa Rica'),
('Cypr',	'Cyprus'),
('Czeska Republika',	'Czech Republic'),
('Dänemark',	'Denmark'),
('Dania',	'Denmark'),
('Demokratische Volksrepublik Korea',	'North Korea'),
('Deutschland',	'Germany'),
('Dominikanische Republik',	'Dominican Republic'),
('Ecuador',	'Ecuador'),
('Egipt',	'Egypt'),
('Estonia',	'Estonia'),
('Färöer (zu Dänemark)',	'Faroe Islands'),
('Falklandinseln',	'Falkland Islands'),
('Finlandia',	'Finland'),
('Finnland',	'Finland'),
('Francja',	'France'),
('Frankreich',	'France'),
('Georgien',	'Georgia'),
('Gibraltar',	'Gibraltar'),
('Grönland',	'Greenland'),
('Grecja',	'Greece'),
('Griechenland',	'Greece'),
('Grönland',	'Greenland'),
('Großbritannien',	'United Kingdom'),
('Hiszpania',	'Spain'),
('Holandia',	'Netherlands'),
('Indie',	'India'),
('Indien',	'India'),
('Irland',	'Ireland'),
('Irlandia',	'Ireland'),
('Island',	'Iceland'),
('Islandia',	'Iceland'),
('Israel',	'Israel'),
('Italien',	'Italy'),
('Jemen',	'Yemen'),
('Kambodża',	'Cambodia'),
('Kanada',	'Canada'),
('Kapverden',	'Cape Verde'),
('Kasachstan',	'Kazakhstan'),
('Kenia',	'Kenya'),
('Kirgistan',	'Kyrgyzstan'),
('Kroatien',	'Croatia'),
('Liechtenstein',	'Liechtenstein'),
('Litwa',	'Lithuania'),
('Luxemburg',	'Luxembourg'),
('Malaysia',	'Malaysia'),
('Malediven',	'Maldives'),
('Malta',	'Malta'),
('Marokko',	'Morocco'),
('Maroko',	'Morocco'),
('Mauritius',	'Mauritius'),
('Mazedonien',	'Macedonia'),
('Mołdawia',	'Moldova'),
('Monako',	'Monaco'),
('Montenegro',	'Montenegro'),
('Namibia',	'Namibia'),
('Nepal',	'Nepal'),
('Neuseeland',	'New Zealand'),
('Niderlandy',	'Netherlands'),
('Niederlande',	'Netherlands'),
('Niederländische Antillen',	'Netherlands Antilles'),
('Niemcy',	'Germany'),
('Norwegen',	'Norway'),
('Norwegia',	'Norway'),
('Österreich',	'Austria'),
('Polen',	'Poland'),
('Polska',	'Poland'),
('Portugal',	'Portugal'),
('Portugalia',	'Portugal'),
('Rosja',	'Russia'),
('Ruanda',	'Rwanda'),
('Rumänien',	'Romania'),
('Rumunia',	'Romania'),
('Russische Föderation',	'Russia'),
('Słowacja',	'Slovakia'),
('Südgeorgien und die Südlichen Sandwichinseln',	'South Georgia and the South Sandwich Islands'),
('Schweden',	'Sweden'),
('Schweiz',	'Switzerland'),
('Serbien',	'Serbia'),
('Serbien und Montenegro',	'Serbia and Montenegro'),
('Seychellen',	'Seychelles'),
('Simbabwe',	'Zimbabwe'),
('Slowenien',	'Slovenia'),
('Słowacja',	'Slovakia'),
('Spanien',	'Spain'),
('Sri Lanka',	'Sri Lanka'),
('Südafrika',	'South Africa'),
('Svalbard und Jan Mayen',	'Svalbard and Jan Mayen'),
('Szwajcaria',	'Switzerland'),
('Szwecja',	'Sweden'),
('Türkei',	'Turkey'),
('Tajlandia',	'Thailand'),
('Thailand',	'Thailand'),
('Togo',	'Togo'),
('Trinidad und Tobago',	'Trinidad and Tobago'),
('Tschad',	'Chad'),
('Tschechische Republik',	'Czech Republic'),
('Tunesien',	'Tunisia'),
('Tunezja',	'Tunisia'),
('Turcja',	'Turkey'),
('Türkei',	'Turkey'),
('Uganda',	'Uganda'),
('Ukraina',	'Ukraine'),
('Ukraine',	'Ukraine'),
('Ungarn',	'Hungary'),
('USA',	'USA'),
('Usbekistan',	'Uzbekistan'),
('Vatikan (Heiliger Stuhl)',	'Holy See'),
('Vereinigte Staaten',	'United States'),
('Vietnam',	'Vietnam'),
('Volksrepublik China',	'China'),
('Włochy',	'Italy'),
('Węgry',	'Hungary'),
('Wielka Brytania',	'United Kingdom'),
('Wietnam',	'Vietnam'),
('Zjednoczone Emiraty Arabskie',	'United Arab Emirates');

-- 2018-05-04 12:27:52
