name: Install Postgis data


runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      run: |
        echo "::group::Install postgis"
        sudo apt-get update
        ${APT_INSTALL} postgis
        echo "::endgroup::"

    - name: Cache SRTM data
      uses: actions/cache@v5
      with:
        path: ./website/db/srtm/*.zip
        key: srtm-cache
        restore-keys: |
          srtm-cache

    - name: Import SRTM data
      shell: bash
      run: |
        ./website/db/tests-srtm-import.sh

    - name: Test SRTM data
      shell: bash
      run: |
        for j in $(seq ${{ env.GK_INSTANCE_COUNT }}); do
          f=$(($j - 1))
          g=$(($j + 9))
          echo "::group::Run basic SRTM tests (5${g}6) ; stack:$f"
          psql --port=5${g}6 -c "SELECT count(*) FROM public.srtm"
          psql --port=5${g}6 -c "SELECT iso_a2 FROM public.countries WHERE public.ST_Intersects(geom::public.geometry, '0101000020E6100000F6285C8FC2F51C405C8FC2F528DC4540'::public.geometry);"
          psql --port=5${g}6 -c "SELECT public.ST_Value(rast, '0101000020E6100000F6285C8FC2F51C405C8FC2F528DC4540'::public.geometry) As elevation FROM public.srtm WHERE public.ST_Intersects(rast, '0101000020E6100000F6285C8FC2F51C405C8FC2F528DC4540'::public.geometry) LIMIT 2;"
          echo "::endgroup::"
        done
