name: Run PHPUnit tests

runs:
  using: "composite"
  steps:
    - name: Install PHP dev tools
      shell: bash
      run: |
        echo "::group::make composer-install-dev"
        ${DOCKER_COMPOSE} exec -i website make composer-install-dev
        echo "::endgroup::"

    - name: Run PHPUnit tests
      shell: bash
      run: |
        ${DOCKER_COMPOSE} exec -i website make test-unit

    - name: Copy PHPUnit tests report from docker container
      shell: bash
      run: |
        ${DOCKER_COMPOSE} cp website:/var/www/geokrety/test-unit-report.html test-unit-report.html
