*** Settings ***
Documentation     Variables for users definitions

*** Variables ***
&{GEOKRETY_1}      name=geokrety01    ref=GK0001    tc=TC0001    id=1    type=0    mission=A journey in heaven
&{GEOKRETY_2}      name=geokrety02    ref=GK0002    tc=TC0002    id=2    type=0    mission=${EMPTY}
&{GEOKRETY_3}      name=geokrety03    ref=GK0003    tc=TC0003    id=3    type=0    mission=${EMPTY}
&{GEOKRETY_4}      name=geokrety04    ref=GK0004    tc=TC0004    id=4    type=0    mission=${EMPTY}
&{GEOKRETY_5}      name=geokrety05    ref=GK0005    tc=TC0005    id=5    type=0    mission=${EMPTY}
&{GEOKRETY_6}      name=geokrety06    ref=GK0006    tc=TC0006    id=6    type=0    mission=${EMPTY}
&{GEOKRETY_7}      name=geokrety07    ref=GK0007    tc=TC0007    id=7    type=0    mission=${EMPTY}

${TC_INVALID}      ABCDEF
