name: Upload translations strings to Crowdin

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      upload:
        type: boolean
        description: 'Push to crowdin?'
        required: true
        default: 'true'

jobs:
  crowdin:
    if: "!contains(github.event.head_commit.message, 'skip translate')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: |
          major_version=$(cut -d '.' -f 1 <<< ${{ github.ref_name }})
          echo "major_version=${major_version}" >> $GITHUB_OUTPUT

          TMP=$(mktemp -d)
          echo "tmp_dir=${TMP}" >> $GITHUB_OUTPUT

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Installing package dependencies
        run: |
          composer install --ignore-platform-reqs --no-interaction
          sudo apt-get install -y gettext moreutils

      - name: Build file list to proceed
        run: |
          find ./website/ -type f -name '*.php' -not -path './website/old/*' -not -path './website/vendor/*' -not -path './website/templates/*' | sort > ${{ steps.vars.outputs.tmp_dir }}/input-files-for-xgettext
          cat ${{ steps.vars.outputs.tmp_dir }}/input-files-for-xgettext

      - name: Generate po file
        run: |
          xgettext --from-code=UTF-8 -o ${{ steps.vars.outputs.tmp_dir }}/messages.pot --language=PHP -f ${{ steps.vars.outputs.tmp_dir }}/input-files-for-xgettext

      - name: Extract strings from smarty templates
        run: |
          ./vendor/bin/tsmarty2c.php -o ${{ steps.vars.outputs.tmp_dir }}/smarty.pot ./website/app-templates ./website/app-templates/smarty/js/*.js

      - name: Concatenate po files
        run: |
          msgcat -o website/app/languages/messages.po.txt ${{ steps.vars.outputs.tmp_dir }}/messages.pot ${{ steps.vars.outputs.tmp_dir }}/smarty.pot

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          config: crowdin.yml
          project_id: 260106
          token: ${{ secrets.CROWDIN_API_KEY }}
          upload_sources: true
          upload_sources_args: --branch ${{ steps.vars.outputs.major_version }}
          upload_translations: false
          download_translations: false
